###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "username" : "abcde",
    "password" : "abcde@123",
    "email": "abcde@gmail.com"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email" : "abcd@gmail.com",
    "password" : "abcde@123"
}